### ISSUE TITLE
xDhcpServerOption Router option

### ISSUE THREAD

**Issue by joes** [dsccommunity/xDhcpServer#37]
It seems that the `Router` option of  `xDhcpServerOption` must always be set? Is there any way to leave it unspecified? If I leave it unspecified I get the following error:

```
The variable cannot be validated because the value System.String[] is not a valid value for the Router variable.
    + CategoryInfo          : MetadataError: (:) [], CimException
    + FullyQualifiedErrorId : ValidateSetFailure
    + PSComputerName        : localhost
```

**Comment by mikejwhat** [comment]
I second this

**Comment by johlju** [comment]
The Router property is set to Write in the schema, but has a [ValidateNotNullOrEmpty()] on it that generates that error message. It looks like if that is removed from the parameter the code could work without specifying `Router` parameter (line 133 could pose a problem).

https://github.com/PowerShell/xDhcpServer/blob/a748ae1965e5a757e4c8916822712b53465670cb/DSCResources/MSFT_xDhcpServerOption/MSFT_xDhcpServerOption.psm1#L97-L98

**Comment by 1RedOne** [comment]
For the meantime, what is this option meant to control?  Can't find it in the documents

**Comment by johlju** [comment]
You are correct, it's missing there, that should be resolved too. If I'm not mistaken its used to set gateway addresses.

**Comment by 1RedOne** [comment]
For those curious, the router option is a really oddly named setting which really corresponds to the default gateway for that DHCP Configuration.  Why isn't this just named 'Default Gateway'

**Comment by johlju** [comment]
For information. @1RedOne updated the documentation in PR #42, but the main issue still need to be resolved.

**Comment by johlju** [comment]
The resource `xDhcpServerOption` was deprecated when the resource `DhcpScopeOptionValue` was released.  The resource `xDhcpServerOption` will be removed in the next release.
