### ISSUE TITLE
Feature Request - Exclusion Range

### ISSUE THREAD

**Issue by Zuldan** [dsccommunity/xDhcpServer#7]
Hi Team, please can you kindly add the ability to add/remove DHCP exclusion ranges. 

Example below; At the moment only Method 1 is available.

Say for instance Network Devices/Servers sit on 192.168.1.1 to 192.168.1.20

Method 1: Scope 192.168.1.21 -> 192.168.1.254

Method 2: Scope 192.168.1.1 -> 192.168.1.254
                 Reservation 192.168.1.1 -> 192.168.1.20

Many organizations use Method 2 as best practice for defining DHCP scopes.

DHCP cmdlets to accomplish this;

Get-DhcpServerv4ExclusionRange
Add-DhcpServerv4ExclusionRange
Remove-DhcpServerv4ExclusionRange

**Comment by cdituri** [comment]
I'm using ``xDhcpServer`` on a client project and require an exclusion range so #dibs if you don't mind ... I'll open a pull request if/when I get a working ``xDhcpServerExclusionRange`` resource completed. Cheers.

**Comment by Zuldan** [comment]
@cdituri, fantastic! Looking forward to it.

**Comment by cdituri** [comment]
@Zuldan - just a ping, see #19. The PR could certainly use an extra set of eyes or another tester if you're up for it. Cheers.

**Comment by johlju** [comment]
@cdituri If you want to continue your work then please reopen you issue and we can work on getting it merged together. 

PR #19 was closed by @cdituri, so relabel this as 'help wanted' again.
