### ISSUE TITLE
xDhcpServerReservation: "The term 'IPAddress' is not recognized" Terminating Error

### ISSUE THREAD

**Issue by jeremysbrain** [dsccommunity/xDhcpServer#73]
#### Details of the scenario you tried and the problem that is occurring

- Code worked properly in v2.0.0.0.
- MOF files build without error
- Running Test-DscConfiguration the code fails with the following errors:

The term 'IPAddress' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (IPAddress:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.WhereObjectCommand
    + PSComputerName        : AD_Server

The PowerShell DSC resource '[xDhcpServerReservation]TEST_Reservation' with SourceInfo 'D:\Documents\WindowsPowerShell\DSC\HQ\AD_Server.ps1::240::9::xDhcpServerReservation'
threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : AD_Server

**Error Event Logs from impacted server:**
TimeCreated  : 1/6/2021 8:09:16 PM
ProviderName : Microsoft-Windows-DSC
Id           : 4252
Message      : Job {0DB3D577-509E-11EB-AAB2-0050568C05D3} :                                                                            MIResult: 1                                                                                                             Error Message: The PowerShell DSC resource '[xDhcpServerReservation]DHCPReservationPrinter-Door1' with                  SourceInfo 'D:\Documents\WindowsPowerShell\DSC\HQ\HQ-AD01.ps1::243::13::xDhcpServerReservation' threw                   one or more non-terminating errors while running the Test-TargetResource functionality. These errors
               are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more
               details.
               Message ID: NonTerminatingErrorFromProvider
               Error Category: 7
               Error Code: 1
               Error Type: MI

TimeCreated  : 1/6/2021 8:09:16 PM
ProviderName : Microsoft-Windows-DSC
Id           : 4252
Message      : Job {0DB3D577-509E-11EB-AAB2-0050568C05D3} :
               MIResult: 1
               Error Message: The term 'IPAddress' is not recognized as the name of a cmdlet, function, script file,
               or operable program. Check the spelling of the name, or if a path was included, verify that the path is
               correct and try again.
               Message ID: CommandNotFoundException,Microsoft.PowerShell.Commands.WhereObjectCommand
               Error Category: 13
               Error Code: 13
               Error Type: MI

TimeCreated  : 1/6/2021 8:09:16 PM
ProviderName : Microsoft-Windows-DSC
Id           : 4103
Message      : Job {0DB3D577-509E-11EB-AAB2-0050568C05D3} :
               This event indicates that a non-terminating error was thrown when DSCEngine was executing
               Test-TargetResource on MSFT_xDhcpServerReservation DSC resource. FullyQualifiedErrorId is
               CommandNotFoundException,Microsoft.PowerShell.Commands.WhereObjectCommand. Error Message is The term
               'IPAddress' is not recognized as the name of a cmdlet, function, script file, or operable program.
               Check the spelling of the name, or if a path was included, verify that the path is correct and try
               again..

#### Verbose logs showing the problem

VERBOSE: [AD_Server]: LCM:  [ Start  Resource ]  [[xDhcpServerReservation]TEST_Reservation]
VERBOSE: [AD_Server]: LCM:  [ Start  Test     ]  [[xDhcpServerReservation]TEST_Reservation]
VERBOSE: [AD_Server]:                            [[xDhcpServerReservation]TEST_Reservation] Evaluating the server reservation with scope id '172.16.15.0' if it is in the
desired state.
VERBOSE: [AD_Server]:                            [[xDhcpServerReservation]TEST_Reservation] Checking DHCP server reservation in scope id 172.16.15.0 for IP address 172.16.0.49
 ...
The term 'IPAddress' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (IPAddress:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.WhereObjectCommand
    + PSComputerName        : AD_Server

VERBOSE: [AD_Server]:                            [[xDhcpServerReservation]TEST_Reservation] DHCP server reservation in the given scope id for the IP address is absent and it
should be Present
VERBOSE: [AD_Server]: LCM:  [ End    Test     ]  [[xDhcpServerReservation]TEST_Reservation] False in 0.4220 seconds.
VERBOSE: [AD_Server]: LCM:  [ *FAILED*Compare  ]     Completed processing compare operation. The operation returned False.
The PowerShell DSC resource '[xDhcpServerReservation]TEST_Reservation' with SourceInfo 'D:\Documents\WindowsPowerShell\DSC\HQ\AD_Server.ps1::240::9::xDhcpServerReservation'
threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : AD_Server

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 21.126 seconds

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        xDhcpServerReservation "TEST_Reservation" {
            Ensure = 'Present'
            Name = 'Printer-Door1'
            ScopeID = '172.16.15.0'
            IPAddress = '172.16.15.49'
            ClientMACAddress = '001122334455'
            AddressFamily = 'IPv4'
            DependsOn = "[xDHCpServerScope]Add-DhcpScope"
        }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
3.0.0-Preview2

**Comment by murphypetercl** [comment]
I'm having same issue - Windows2016.

Looks like it doesn't like the -FilterScript

$reservation = Get-DhcpServerv4Reservation -ScopeID $ScopeID | Where-Object -FilterScript {
        IPAddress -eq $IPAddress
    }

Maybe change to:
$reservation = Get-DhcpServerv4Reservation -ScopeID $ScopeID | Where-Object IPAddress -eq $IPAddress

**Comment by rayterrill** [comment]
Running into this issue - has this fix made it into a release?

**Comment by ZanattaMichael** [comment]
@johlju  @PlagueHO  @danielboth  @gaelcolas @regedit32 @ykuijs

**Comment by gaelcolas** [comment]
Thanks for bringing it to our attention.
We're happy to help people get moving, I guess we should look into #77 ? (please help pointing me to this)

There are some ~50 repositories  that @PlagueHO @johlju and myself are admin on, so we can't see GH notifications (not even when you tag us).
If the module's maintainer (if any) does not answer, come the PS/Discord slack, DSC channel and ping us (I'm almost always there, CET until ET times). Worst case, ask us on twitter.

From there I'll try to ping the current maintainer or if there's none available, try to find someone to do a first review.
Anyone can start a review and give feedback. The first review is what takes most time, because we'll do a thorough review, ask for some changes, and people won't follow-up with it.

The thing to check in a review:
- Does the change break anything (if the tests do not pass, we probably won't look further)
- Are the changes in line with the Style and Rules for HQRM modules
- Do the change/design makes sense for a DSC concept (usually idempotency, conflicting keys, atomic changes knd of ideas)

The more contributions someone makes, the more trust we have, and the more skills that person picks up. So we can make that person a maintainer.
